---
- name: Rackspace Cloud Controller | check rackspace_username
  fail:
    msg: "rackspace_username is missing (OS_USERNAME)"
  when:
    - rackspace_username is not defined or not rackspace_username


- name: Rackspace Cloud Controller | check rackspace_api_key value
  fail:
    msg: "rackspace_api_key is missing (RAX_API_KEY)"
  when:
    - rackspace_api_key is not defined or not rackspace_api_key


- name: Rackspace Cloud Controller | check rackspace_region value
  fail:
    msg: "rackspace_region is missing (OS_REGION_NAME)"
  when: rackspace_region is not defined or not rackspace_region


- name: Rackspace Cloud Controller | check rackspace_tenant_id value
  fail:
    msg: "rackspace_tenant_id is missing (OS_TENANT_ID)"
  when:
    - rackspace_tenant_id is not defined or not rackspace_tenant_id
