---
- name: Rackspace Cloud Controller | check rackspace_username
  fail:
    msg: "rackspace_username is missing"
  when:
    - rackspace_username is not defined or not rackspace_username


- name: Rackspace Cloud Controller | check rackspace_password value
  fail:
    msg: "rackspace_password is missing"
  when:
    - rackspace_password is not defined or not rackspace_password


- name: Rackspace Cloud Controller | check rackspace_region value
  fail:
    msg: "rackspace_region is missing"
  when: rackspace_region is not defined or not rackspace_region


- name: Rackspace Cloud Controller | check rackspace_tenant_id value
  fail:
    msg: "rackspace_tenant_id is missing"
  when:
    - rackspace_tenant_id is not defined or not rackspace_tenant_id
